### ISSUE TITLE
hey my friend cant even download the fucking patche rhodajfjklsdj

### ISSUE THREAD

**Issue by GabrielSomething** [coop-deluxe/coopdx-patcher#4]
![image](https://github.com/coop-deluxe/coopdx-patcher/assets/49927160/37f52c45-a9aa-4f8e-9e74-08313e016d9b)

windows defender shows that and cancels the download from his browser automatically
(sorry that the image is literally spanish lkajflkda)

**Comment by Slimyiscool** [comment]
Just click allow download its just saying not downloaded regularly i think
