### ISSUE TITLE
Possible DirectX 11 option?

### ISSUE THREAD

**Issue by RayTheMaymay** [coop-deluxe/coopdx-patcher#8]
Hey, so, I'm most likely in a very specific situation for this to be warranted, but atm I'm GPU-less and solely able to play SM64excoop thanks to the DirectX 11 build option. I'd have been on CoopDX already by now with all the improvements if it weren't for the fact the only DirectX version that it allows for is DirectX 12.

I'd appreciate it if support for DirectX 11 was added someday at least, since I'd love to continue playing SM64 co-op through this build 🙏~

**Comment by Agent-11** [comment]
Will do!
