### ISSUE TITLE
i need the linux version

### ISSUE THREAD

**Issue by TemaisgameNoobas** [coop-deluxe/coopdx-patcher#9]
i NEEEEEEEEEEED the linux version cuz IM ON LINUX

**Comment by TemaisgameNoobas** [comment]
https://github.com/coop-deluxe/sm64coopdx

oh nvm im just dumb

**Comment by Kazajin** [comment]
Wait, why close? There's no linux version of the patcher.

**Comment by TemaisgameNoobas** [comment]
you can compile it yourself I guess..

> Wait, why close? There's no linux version of the patcher.
